dataquestio/solutions

README.md
=> add new project to readme

Mission288Solutions.ipynb
Changed title as per Srini's suggestion and corrected a typo
=> Changed title as per Srini's suggestion and corrected a typo

Mission217Solutions.ipynb
@srinify Not sure who to notify
Addresses https://gitlab.dataquest.io/dataquestio/dscontent/issues/1128
=> Address Gitlab Issue 1128

Mission213Solution.ipynb
Resolves https://gitlab.dataquest.io/dataquestio/dscontent/issues/960
=> Resolve Gitlab issue #960

Mission244Solutions.ipynb
=> M244 Solutions

Mission350Solutions.ipynb
To be merged only after PR 78 is merged and deployed to prod: https://github.com/dataquestio/content/pull/78
=> M350 -- bug fixing

Mission356Solutions.ipynb
Rewrite of the solution of Py2's GP without list comprehension, nor regex.
=> Py2 GP Solution Rewrite

Mission155Solutions.ipynb
Branch to fix https://app.asana.com/0/1109607871564464/1141768947553998/f
=> Fix https://app.asana.com/0/1109607871564464/1141768947553998/f

Mission459Solutions.Rmd
Linear Modeling in R course ready for launch. Adding Guided Project Solutions.
=> Adding M459/Guided Project solutions

Mission350Solutions.ipynb
Branch to fix https://app.asana.com/0/1109607871564464/1159401741654574/f
=> Fix GP 350's Solution

Mission257Solutions.ipynb
Bug to fix https://app.asana.com/0/1109607871564464/1164821369537010/f
=> Fix bug on 257

Mission257Solutions.ipynb
Added narrative and fixed for style
=> Optimize solutions

Mission210Solution.ipynb
Fix [this](https://app.asana.com/0/1109607871564464/1172722244320086/f) bug.
=> Refine data cleaning

Mission469Solutions.ipynb
Implement [this](https://community.dataquest.io/t/enumerate-vs-pandas-dataframe-iterrows/452675?u=bruno) community's feedback.
=> Use pandas methods

Mission505Solutions.Rmd, Mission518Solutions.Rmd
Here is the PR of the course https://github.com/dataquestio/content/pull/623
=> Data structure course GP in R

Mission277Solutions.Rmd, Mission327Solutions.Rmd
update ggplot syntax to match convention M277 & 327.
=> [WIP] Feature/casey/ggplot syntax

Mission350Solutions.ipynb, Mission356Solutions.ipynb
Rerun solutions with Python 3.8 for guided projects 350, and 356.
=> Rerun solutions for some guided projects with Python 3.8

Mission267Solutions.ipynb
Reran guided project solution with Py 3.8. This changed the output because of changes to dictionary ordering from Py 3.7+
=> Rerun GP with Py 3.8 267

Mission294Solutions.ipynb
Upgrading mission to run on Py 3.8
=> Rerun Mission294Solutions.ipynb in Python 3.8

600Solutions.sql
=> Course SQL V - GP Sols - 600

Mission735Solutions.ipynb
Adding the solution file for Logistic Regression Modeling in Python
=> Logistic Regression Solution Notebook

Mission804Solutions.ipynb
Solution file for the updated Introduction to Python Programming course.
=> 804 Solutions

Mission903Solutions.py, Mission909Solutions.ipynb
=> Solutions for 903 and 909
